In [7]:
import pandas as pd

base = pd.read_csv(fr'db\base_vendas.csv', sep=';', dtype=str encoding='iso-8859-1')

base

,DATA VENDA,NOME,TELEFONE,QTD,PRODUTO,SABOR,VALOR UNIDADE,TOTAL DA COMPRA,STATUS PEDIDO,TIPO PAGAMENTO,DATA PG
0,06/09/2024,Matheus Rocha,2.195936e+10,1,COPO RECHEADO,NaN,"R$ 15,00","R$ 15,00",PAGO,PIX,06/09/2024
1,06/09/2024,Luana Guimaraes,2.196928e+10,1,CAIXA SIMPLES,NaN,"R$ 10,00","R$ 10,00",PAGO,PIX,06/09/2024
2,06/09/2024,Marco Antonio,2.196935e+10,1,CAIXA SIMPLES,NaN,"R$ 10,00","R$ 10,00",PAGO,DINHEIRO,06/09/2024
3,06/09/2024,Thaina Ramos,2.197400e+10,1,CAIXA SIMPLES,NaN,"R$ 10,00","R$ 10,00",PAGO,PIX,06/09/2024
4,06/09/2024,Thaina Ramos,2.197400e+10,1,COPO RECHEADO,NaN,"R$ 15,00","R$ 15,00",PAGO,PIX,06/09/2024
...,...,...,...,...,...,...,...,...,...,...,...
520,04/02/2024,Gustavo Betzler,NaN,1,COOKIE,TRADICIONAL,"R$ 12,00","R$ 12,00",PENDENTE DE PAGAMENTO,PIX,06/02/2025
521,04/02/2024,Antonio Durão,NaN,1,COOKIE,DUO CHOCOLATE,"R$ 12,00","R$ 12,00",PAGO,PIX,04/02/2024
522,04/02/2024,Antonio Durão,NaN,1,COOKIE,RED VELVET,"R$ 12,00","R$ 12,00",PAGO,PIX,04/02/2024
523,04/02/2024,Dayane da Silva,NaN,1,BROWNIE,DOCE DE LEITE,"R$ 9,00","R$ 9,00",PAGO,PIX,04/02/2024
524,04/02/2024,Thaina Ramos,NaN,1,BROWNIE,LEITE NINHO,"R$ 9,00","R$ 9,00",PENDENTE DE PAGAMENTO,PIX,06/02/2025